name: .NET Core Tests and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: IndFusion.Exxerpro/IndFusion.Exxerpro.sln
      Test_Project_Path: src/IndFusion.ExxerproTests/IndFusion.ExxerproTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    - name: Run tests and collect coverage
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }} --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Convert coverage to lcov
      run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:lcov

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
        parallel: true
